openapi: 3.0.2
info:
  title: Test Spec
  description: see https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/
  version: '0.6'
servers:
- url: http://localhost:8080
paths:
  /:
    get:
      description: 'Get list of models'
      operationId: get
      tags:
      - model
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Model'
components:
  schemas:
    Model:
      discriminator:
        propertyName: type
        mapping:
          Model1: '#/components/schemas/Model1'
          Model2: '#/components/schemas/Model2'
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    Model1:
      allOf:
      - $ref: '#/components/schemas/Model'
      - properties:
          a:
            type: string
    Model2:
      allOf:
      - $ref: '#/components/schemas/Model'
      - properties:
          b:
            type: string
