openapi: 3.0.2
info:
  title: Test Spec
  version: '0'
servers:
- url: http://localhost:8080
paths:
  /:
    get:
      operationId: unsecured
      tags:
      - security
      responses:
        200:
          description: Ok.
  /secured:
    get:
      operationId: secured
      tags:
      - security
      responses:
        200:
          description: Ok.
        401:
          description: Unauthorized.
  /secured/admin:
    get:
      operationId: securedAdmin
      tags:
      - security
      responses:
        200:
          description: Ok.
        401:
          description: Unauthorized.
        403:
          description: Forbidden.
