name: Release

on:
  workflow_dispatch:
    inputs:
      versionLevel:
        description: 'Increase <(M)ajor.(m)inor.(p)atch>'
        required: true
        default: 'p'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: git-configure
      run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
    - name: setup
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: sonatype-nexus
        server-username: SERVER_USERNAME
        server-password: SERVER_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
    - name: determine version
      id: version
      uses: Benbentwo/increment-semver@master
      with:
        version-level: '-${{ github.event.inputs.versionLevel }}'
    - name: dependencies
      run: mvn -B -q dependency:go-offline
    - name: prepare
      run: mvn -B release:prepare
    - name: perform
      run: mvn -B release:perform -DreleaseProfiles=oss-release
      env:
        SERVER_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
        SERVER_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

